version: '3.8'

services:
  bot:
    image: ghcr.io/azdevz/hyperscalp-client:latest
    container_name: hyperscalp-bot
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
